version: "3.3"

services:
  db:
    image: andresvidal/rpi3-mongodb3:latest
    networks:
      - mediacenterb
    ports:
      - 27017:27017

  mediacenterb:
    image: mediacenterb:0.9.2
    build: .
    environment:
      - MEDIACENTER_SETUP=1
      - MEDIACENTER_TVGO_SETUP=1
      - MEDIACENTER_MONGODB_ADDRESS=mongodb://db:27017/mediacenter
      - MEDIACENTER_MONGODB_THUMB_ADDRESS=mongodb://db:27017/movbsthumb
      - MEDIACENTER_LOG_BASE_PATH=/root/logs
      - MEDIACENTER_MOVIES_PATH=/root/fsData/Movies
      - MEDIACENTER_TVSHOWS_PATH=/root/fsData/TVShows
      - MEDIACENTER_HARDRIVE_POSTERS_PATH=/root/fsData/Posters2
      - MEDIACENTER_NO_ART_PIC_PATH=./static/images/animals.jpg
      - MEDIACENTER_THUMB_BASE_PATH=./static/images/thumbnails
      - MEDIACENTER_THUMBNAIL_PIC_PATH=/static
      - MEDIACENTER_TEMPLATE_ADDRESS=./static/templates/mediacenter.template
      - MEDIACENTER_SERVER_PORT=8888
      - MEDIACENTER_SERVER_ADDRESS=http://192.168.0.94
      - MEDIACENTER_OMXPLAYER_ADDRESS=http://192.168.0.94:8181/OmxplayerPlayMedia
      - MEDIACENTER_OMXPLAYER_ADDRESS_REACT=http://192.168.0.94:8181/OmxplayerPlayMediaReact
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - mediacenterb
    ports:
      - 8888:8888
    volumes:
      - mediacentervol:/root/fsData/
      - mediacenterpicvol:/root/static/
      - mediacenterlogvol:/root/logs/
    depends_on:
      - db

networks:
  mediacenterb:

volumes:
  mediacentervol:
    driver: local
    driver_opts:
      type: none
      device: /media/pi/PiTB/media
      o: bind

  mediacenterpicvol:
    driver: local
    driver_opts:
      type: none
      device: /home/pi/Thumbnails
      o: bind

  mediacenterlogvol:
    driver: local
    driver_opts:
      type: none
      device: /home/pi/LOGFILES
      o: bind


