version: "3.3"

services:
  db:
    image: andresvidal/rpi3-mongodb3:latest
    networks:
      - mediacenterb
    ports:
      - 27017:27017
    # volumes:
    #   - mongovol:/data/db

  mediacenterb:
    image: mediacenterb:0.0.2
    build: .
    environment:
      - mediacenter_SETUP=1
      - mediacenter_MONGODB_ADDRESS=mongodb://db:27017/mediacenter
      - mediacenter_MONGODB_THUMB_ADDRESS=mongodb://db:27017/movbsthumb
      - mediacenter_MOVIES_PATH=/root/fsData/Movies
      - mediacenter_TVSHOWS_PATH=/root/fsData/TVShows
      # - mediacenter_POSTERS_PATH=/root/fsData/Thumbs
      - mediacenter_HARDRIVE_POSTERS_PATH=/root/fsData/Posters2
      # - mediacenter_HARDDRIVE_POSTERS_PATH=/root/fsData/Posters
      
      - mediacenter_NO_ART_PIC_PATH=./static/images/animals.jpg
      - mediacenter_THUMB_BASE_PATH=./static/images/thumbnails
      # - mediacenter_THUMBNAIL_PIC_PATH=./static/images/thumbnails
      - mediacenter_THUMBNAIL_PIC_PATH=/static
      - mediacenter_TEMPLATE_ADDRESS=./static/templates/mediacenter.template
      - mediacenter_SERVER_PORT=8888
      - mediacenter_SERVER_ADDRESS=http://192.168.0.42
      - mediacenter_OMXPLAYER_ADDRESS=http://192.168.0.42:8181/OmxplayerPlayMedia
      - mediacenter_OMXPLAYER_ADDRESS_REACT=http://192.168.0.42:8181/OmxplayerPlayMediaReact
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - mediacenterb
    ports:
      - 8888:8888
    volumes:
      - mediacentervol:/root/fsData/
      - mediacenterpicvol:/root/static/
    depends_on:
      - db

networks:
  mediacenterb:

volumes:
  mediacentervol:
    driver: local
    driver_opts:
      type: none
      device: /media/pi/PiTB/media
      o: bind

  mediacenterpicvol:
    driver: local
    driver_opts:
      type: none
      device: /home/pi/Thumbnails
      o: bind



